// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ManageChildVC
{
    public partial class FirstChildViewController : UIViewController
    {
        public FirstChildViewController(IntPtr handle) : base(handle)
        {
        }

        partial void UIButton2A9ndvhV_TouchUpInside(UIButton sender)
        {
            //throw new NotImplementedException();
        }
    }
}
