// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace ManageChildVC
{
    public partial class SecondChildViewController : UIViewController
    {
        public SecondChildViewController(IntPtr handle) : base(handle)
        {
        }

        partial void UIButtonO6y5IbpT_TouchUpInside(UIButton sender)
        {
            //throw new NotImplementedException();
        }
    }
}
