// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace ChildViewControlleriOSDemo
{
    public partial class BookingsViewController : UIViewController
    {
        public BookingsViewController(IntPtr handle) : base(handle)
        {
        }
    }
}
