// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ChildViewControlleriOSDemo
{
	public partial class StatisticsViewController : UIViewController
	{
		public StatisticsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
